name: Increment Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'The type of version to increment: major, minor, or patch'
        required: true
        options:
          - patch
          - minor
          - major


jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Increment version
        run: |
          npm version --git-tag-version ${{ github.event.inputs.version_type }}
          echo "New version: $(node -p "require('./package.json').version")"

      - name: Commit changes
        run: |
          git commit -a -m "Bump version to $(node -p "require('./package.json').version")"
          git tag -a -m "Version $(node -p "require('./package.json').version")" $(node -p "require('./package.json').version")
          git push origin --follow-tags

      - name: Fast-forward merge publish branch to main
        run: |
          git checkout main
          git merge --ff-only publish
          git push