name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'The type of version to increment: major, minor, or patch'
        required: true
        options:
          - patch
          - minor
          - major

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git status

      - name: Install dependencies
        run: npm ci

      - name: Increment version
        run: |
          npm version --no-git-tag-version ${{ github.event.inputs.version_type }} -m "Release version to v%s"
          VERSION="v$(node -p "require('./package.json').version")"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version: ${VERSION}"
          git add package.json
          git add package-lock.json

      - name: Update Change Log
        env:
          CHANGE_LOG_FILE: "CHANGELOG.md"
        run: |
          npx auto-changelog --commit-limit false -p --output ${CHANGE_LOG_FILE}
          git add ${CHANGE_LOG_FILE}

      - name: Push commit and tag
        run: |
          git commit -m "Release version ${VERSION}"
          git push
          git tag ${VERSION}
          git push origin ${VERSION}

  buildpublish:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run compile
        run: npm run compile


      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com

