name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'The type of version to increment: major, minor, or patch'
        required: true
        options:
          - patch
          - minor
          - major

env:
  RELEASE_BRANCH: release

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git status

      - name: Install dependencies
        run: npm ci

      - name: Increment version
        run: |
          npm version --git-tag-version ${{ github.event.inputs.version_type }} -m "Release version to v%s"
          VERSION="v$(node -p "require('./package.json').version")"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version: ${VERSION}"

      - name: Update Change Log
        run: |
          npx auto-changelog --commit-limit false --stdout > CHANGELOG.md
          git add CHANGELOG.md
          git commit --amend --no-edit

      - name: Push changes
        run: |
          git push --follow-tags

      - name: Fast-forward merge publish branch to main
        run: |
          git push --force-with-lease origin +${VERSION}~0:${RELEASE_BRANCH}

  buildpublish:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run compile
        run: npm run compile


      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com

