name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'The type of version to increment: major, minor, or patch'
        required: true
        options:
          - patch
          - minor
          - major

env:
  RELEASE_BRANCH: release

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          echo "git status"
          git status

      - name: Install dependencies
        run: npm ci

      - name: Increment version
        run: |
          npm version --git-tag-version ${{ github.event.inputs.version_type }} -m "Release version to v%s"
          git push --follow-tags
          VERSION="v$(node -p "require('./package.json').version")"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version: ${VERSION}"

      - name: Fast-forward merge publish branch to main
        run: |
          git push --force origin +${VERSION}~0:${RELEASE_BRANCH}
